url: https://mbtest5a.github.io
baseurl: /

# Site settings
title: LivApp Inc.
email: careers@mixerbox.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 37b9eb
  secondary: 9bdcf5
  secondary-dark: 333
  
header1: 想一同打造世界最大的音樂社群嗎？
header2: Join us

# Team names, titles and social links
people:
- name: John Lai
  pic: 1
  position: Chairman & CEO
  info:
    - title: 美國哈佛大學

- name: Vera Huang
  pic: 2
  position: Marketing
  info:
    - title: 國立政治大學

- name: Carlos Chen
  pic: 3
  position: iOS Engineer
  info:
    - title: 國立政治大學
      
- name: Ariel Shih
  pic: 3
  position: Android Engineer
  info:
    - title: 國立台灣大學
    - title: 美國國際科展台灣代表
      
- name: David Hsu
  pic: 3
  position: Backend Engineer
  info:
    - title: 國立台灣大學
      
- name: Eric Chen
  pic: 3
  position: iOS & Android Engineer
  info:
    - title: 國立台灣大學
    - title: 資訊奧林匹亞銅牌
      
- name: Katie Huang
  pic: 3
  position: HR Specialist
  info:
    - title: 國立台灣大學
      
- name: Chen-Yu Yang
  pic: 3
  position: Data Scientist
  info:
    - title: 國立台灣大學
    - title: 數學奧林匹亞銀牌
      
- name: Shiva Huang
  pic: 3
  position: iOS Engineer
  info:
    - title: 國立台灣大學
      
- name: Yufan Ho
  pic: 3
  position: Backend Engineer
  info:
    - title: 國立台灣大學
    - title: 資訊奧林匹亞銀牌
      
- name: Shik Chen
  pic: 3
  position: Intern Engineer
  info:
    - title: 國立台灣大學
    - title: 資訊奧林匹亞金牌

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Hiring information
hiring:
- name: iOS Engineer
  pic: 1.png
  position: 負責iOS App新功能開發與維護

- name: Android Engineer
  pic: 2.png
  position: 負責Android App新功能開發與維護

- name: Cloud Backend Engineer
  pic: 3.png
  position: 負責網站新功能開發與後端維護
  
- name: Web Engineer
  pic: 4.png
  position: 負責網站架設與維護
  
- name: Marketing
  pic: 5.png
  position: 讓更多人成為 MixerBox 的愛用者

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty